//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public string MaPhieuMuon { get; set; }
        public string MaSinhVien { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTraDuKien { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public string MaSach { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
