//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaLoaiSach { get; set; }
        public Nullable<int> NamXB { get; set; }
        public string MaNXB { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaViTri { get; set; }
        public string MaTacGia { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<System.DateTime> TimeCreate { get; set; }
        public Nullable<System.DateTime> TimeUpdate { get; set; }
        public string ImagePath { get; set; }
    
        public virtual NXB NXB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        public virtual ViTri ViTri { get; set; }
    }
}
