//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Ma_LoaiTK { get; set; }
    
        public virtual LOAI_TAIKHOAN LOAI_TAIKHOAN { get; set; }
    }
}
